
/* Editor.c */
void DoHelpEditor(short **, short *);
Cmd *GetCmd(short, short, Pcmd *);
void ConvertPointAndType(Point *, short *);
Cmd *GetEditorSelectCmd(short *, short *);
void SetSelectionEditor(short, short, short);
void SetMaxWindow(short, short, DialogPtr);
void SelectCurrentActif(void);
void OctavesName(short, Ptr);
short ConvertNote2No(Str32);
void CheckColumn(void);
void OutPutHexShort(Str255, short, short);
void NTStr(short, short, Ptr);
void SetPatternCell(short, short);
void GetNoteString(short, Str255);
void InitStringEditor(void);
Boolean CreateNoteString(Cmd *, Str255, Boolean);
void SetNewPat(void);
void UpdateEditorInfo(void);
void CreateCurRect(void);
void DrawLeft(RgnHandle, Boolean);
void DrawEditorUp(void);
void DoNullEditor(void);
void DoGrowPartition(void);
void DrawGrowIconP(DialogPtr);
void DrawEditorLegende(void);
void DrawGrayLines(short);
void DrawMarkers(short, short);
void DrawSelectionZone(Rect *);
void MyLUpdate(void);
void MyLUpdateSpecific(short, short);
void UpdatePartitionWindow(DialogPtr);
void GetDigitalSelection(short *, short *, short *, short *, short *);
void SetDigitalSelection(short, short, short, short);
void CalculDiffStart(void);
void DragSelect(void);
void SavePcmdFile(Pcmd *);
void OpenPcmdFile(FSSpec *);
Boolean MLClick(Point, short);
void DoItemPressPartition(short, DialogPtr);
void UpdateCompleteEditor(void);
void PLScrollIntPartition(short, short, long);
void CreatePartitionWindow(void);
void InternalEditorInit(void);
void ClosePartitionWindow(void);
void DigitalEditorProcess(short, short*, short*, short*);
void DoKeyPressEditor(short);
Ptr ConvertPcmd2Text(Pcmd *);
Pcmd *CreatePcmdFromSelection(void);
void ApplyOnAllCell(short, short, short, short, short);
void PasteCmdEditor(Point, Pcmd *);
void COPYEditor(void);
void PASTEEditor(void);
void EraseHilite(Rect *);
pascal OSErr MyTrackingEditor(short, WindowPtr, void *, DragReference);
pascal OSErr MySendDataProcEditor(FlavorType, void *, ItemReference, DragReference);
Boolean DragEditor(RgnHandle, Pcmd *, EventRecord *);
pascal OSErr MyReceiveDropEditor(WindowPtr, void*, DragReference);
void PrintEditor(void);
