
/* Main.c */
void CreateTempFile(void);
void DeleteTempFile(void);
void MyDebugStr(short, Ptr, Ptr);
void CloseALLWindow(void);
void TESTBugs(void);
void SKVolume(short);
void ClosePlayerWindow(DialogPtr);
void SetWindEtat(WindowPtr);
void CheckOneWindow(WindowPtr);
void CheckShowWindow(void);
void ShowWindowPref( short);
WindowPtr NextWindowVisible(WindowPtr);
void EraseGrowIcon(DialogPtr);
void SelectWindow2(WindowPtr);
void SysCheck(void);
void Switch(void);
void DeSwitch(void);
void MusiqueDriverInit(void);
Handle MyNewHandle(long);
void MyDisposHandle(Handle *);
Ptr MyNewPtr(long);
void MyDisposPtr(Ptr *);
short doDlgEvt(EventRecord *);
void DoGlobalNull(void);
void GlobalDoKey(WindowPtr, char);
void ActivateProcedure(Boolean);
void DoOSEvent(EventRecord *, Boolean);
void EventLoop3(void);
void EventLoop2(void);
void EventLoop(void);
pascal short MyGetDirHook(short, DialogPtr);
void UseSameLeft(WindowPtr);
Boolean TrackInHelpButton(WindowPtr, Point);
void DoMouseDown(EventRecord);
void DoUpdateEvent(EventRecord*);
void UpdateALLWindow(void);
Boolean PtRect(Point, Rect *);
void DrawVERSION(void);
void StartDialog(void);
void EndDialog(void);
pascal Boolean MyCustomFileFilter2(CInfoPBRec*, void *);
void WriteSupportedFormat(DialogPtr);
pascal short MyDlgHook2(short, DialogPtr, void *);
OSErr NGetFileName(FSSpec *);
OSErr DoCustomOpen( FSSpec	*spec);
void NOpenMusic(void);
void InitImportMenu(void);
void MenuBarInit(void);
short IntInfoL(short);
short InfoL(short);
void MADErreur(OSErr);
void IntErreur(short, OSErr);
void Erreur(short, OSErr);
OSErr GereChanged(void);
void HandleMenuChoice(long);
void HandleAppleChoice(short);
void HandleInstruChoice(short);
void HandleViewsChoice(short);
void HandlePatternChoice(short);
void HandleOtherChoice(short);
void WritePreferences(void);
void DeletePreferences(void);
void DoPreferences(void);
void HandleEdit(short);
void HandleFileChoice(short);
void HandleExportFile(short);
void HandleWindowChoice(short theItem);
void HandleHelpChoice(short theItem);
void HandleNewSound(short);
