
/* Oscillo.c */
void DoHelpOscillo(short **, short *);
void GetWorkingZone(Rect *);
void AdjustZoomOscillo2(Rect *);
void ComputeCurrentQuickPixMap(void);
void SetControlOscillo(void);
void DoGrowOscillo(void);
Ptr TransformationDSP(Ptr, short);
Ptr Transformation8(Ptr);
Ptr Inverse8(register Ptr, long);
Ptr Inverse16(register Ptr, long);
Ptr GetAudioChannel(Boolean, long);
Ptr GetAudioInPut(Boolean, long);
void C16BitOsci(short, short, short, Byte *, Byte *);
void C16BitOsciDirect(short, short, short, Byte *, Byte *);
void C8BitOsci(short, short, short, Byte *, Byte *);
void C8BitOsciDirect(short, short, short, Byte *, Byte *);
void C8BitOsciPixMap(Byte *, Byte *, Ptr);
//void DrawOscilloscope2(OsciRec *, short, Boolean);
void DoNull(void);
void FillInterText(Rect *, short);
void UpdateOscilloWindow(DialogPtr);
pascal void actionProcOscillo(ControlHandle, short);
void DoItemPressOscillo(short, DialogPtr);
void SetWindowEnviron(void);
void InitOscillo(void);
long GetAudioSize(void);
Ptr GetAudioSource(short);
void CreateOscilloWindow(void);
void CloseOscillo(void);
void ResetOscilloscope(void);
