
/* Pattern.c */
void DoHelpPatList(short **, short *);
Boolean DragPatternFunction(RgnHandle, short, EventRecord *);
void ActivePatternMenu(Boolean);
void DeleteAPattern(Boolean);
void SaveAPatternInt(FSSpec, short);
void SaveAPattern(void);
void LoadAPatternInt(FSSpec, short);
void LoadAPattern(void);
void AddAPattern(void);
void PurgePattern(void);
void UpdatePatListInfo(void);
short GetPatternSelect(void);
void SetSpeed(PatData *, short);
void SetFineSpeed(PatData *, short);
short GetSpeed(PatData *);
short GetFineSpeed(PatData *);
Boolean DialogPatternInfo(short);
void DoGrowPatList(DialogPtr);
void UpdatePatListWindow(DialogPtr);
void DoNullPattern(void);
void DoReplace(void);
void DialogTracks(void);
void DoItemPressPatList(short, DialogPtr);
void SetPatList2(ListHandle);
void CreatePatListWindow(void);
void ClosePatList(void);
void DuplicatePattern(short);
void DoUpDown(short, ListHandle);
void DoKeyPressPatList(short);
void COPYPatList(void);
void PASTEPatList(void);
