
/* Record.c */
void ActiveControl(short, DialogPtr);
void InactiveControl(short, DialogPtr);
void UpdateSoundQualityExportSndWindow(DialogPtr);
OSErr NSoundQualityExportSnd(short, short, OSType *, Str255);
void Convert8to16(Ptr, Ptr, long);
void Convert16to8(Ptr, Ptr, long);
void ConvertInstrumentAmpli(sData *, short);
void ConvertInstrument( Byte *,  long);
void ConvertInstrument16( short *,  long);
void ConvertInstrumentIn( Byte *,  long);
void ConvertInstrumentIn16( short *,  long);
void CopyInstruInFile(Ptr, Ptr, long);
void SetUpPartition(short);
void GetInstruName(short, Ptr);
void SetInstruName(short, Str255);
void SetSampName(short, short, Str255);
pascal Boolean MyFilterPro(DialogPtr, EventRecord *, short *);
Handle DoExp1to3(Handle, unsigned long);
Handle DoExp1to6(Handle, unsigned long);
Handle NSndToHandle(Handle, long *, long *, short *, unsigned long *, long *, Boolean *);
void RecordSample(void);
void CopyResource(OSType, short, short);
void SaveMOD(Boolean, OSType);
OSErr NOpenSampleInt(short, short, FSSpec);
void NPASTESample(long, short, short);
void NCOPYSample(long, long, short, short);
void AddLoopToSndHandle(Handle, long, long);
void NSaveSampleInt(short, short, OSType, FSSpec *);
void SaveSample(void);
void CreateNewMOD(void);
